FizzBuzzSolution/Web/Models/FizzBuzzModel.cs
using DTO;
using PagedList;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Web.Models
{
    /// <summary>
    /// Fizz buzz input model.
    /// </summary>
    public class FizzBuzzModel
    {
        /// <summary>
        /// Gets or sets number.
        /// </summary>
        [DisplayName("Enter a number.")]
        [Required(ErrorMessage = "Please enter a number.")]
        [RegularExpression("[+]?([0-9]+(?:[\\.][0-9]*)?|\\.[0-9]+)", ErrorMessage = "Enter only positive numbers")]
        [Range(1, 1000, ErrorMessage = "Enter a number between 1 and 1000.")]
        public int Number { get; set; }

        /// <summary>
        /// Gets or sets fizz buzz list.
        /// </summary>
        public PagedList<FizzBuzzDto> FizzBuzzList { get; set; }
    }
}

FizzBuzzSolution/Web/Controllers/FizzBuzzController.cs
using Business;
using DTO;
using PagedList;
using System.Web.Mvc;
using Utilities;
using Web.Models;

namespace Web.Controllers
{
    /// <summary>
    /// Fizz buzz controller for generating fizz buzz list.
    /// </summary>
    public class FizzBuzzController : Controller
    {
        #region Private members

        /// <summary>
        /// Fizz buzz generator.
        /// </summary>
        private readonly IFizzBuzzGenerator fizzBuzzGenerator;
        #endregion

        #region Constructor
        /// <summary>
        /// 
        /// </summary>
        /// <param name="httpClient">Http client for calling rest service.</param>
        public FizzBuzzController(IFizzBuzzGenerator fizzBuzzGenerator)
        {
            this.fizzBuzzGenerator = fizzBuzzGenerator;
        }
        #endregion

        /// <summary>
        /// Renders fizz buzz index view.
        /// </summary>
        /// <returns> Returns view.</returns>
        public ActionResult Index()
        {
            var fizzBuzzInputModel = new FizzBuzzModel();
            return View(fizzBuzzInputModel);
        }

        /// <summary>
        /// Renders view for showing fizz buzz list.
        /// </summary>
        /// <param name="input">Input model details.</param>
        /// <returns>Returns view.</returns>
        //[HttpGet]
        public ActionResult GetFizzBuzzList(FizzBuzzModel input, int page = 1, int pageSize = 20)
        {
            ParamGuard.VerifyArgument(input, "FizzBuzzInputModel cannot be empty or null.");

            var fizzBuzzList = this.fizzBuzzGenerator.Generate(new FizzBuzzRequest { Number = input.Number }).FizzBuzzList;
            PagedList<FizzBuzzDto> pagedList = new PagedList<FizzBuzzDto>(fizzBuzzList, page, pageSize);
            return View("Index", new FizzBuzzModel { Number = input.Number, FizzBuzzList = pagedList });
        }
    }
}

FizzBuzzSolution/Web/Views/FizzBuzz/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model Web.Models.FizzBuzzModel

<div>

    @Html.BeginForm("GetFizzBuzzList", "FizzBuzz"){
        <div class="col-md-4">
            @Html.LabelFor(model => model.Number)
            @Html.ValidationMessageFor(model => model.Number)
            @Html.TextBoxFor(model => model.Number)
            <input type="submit" id="button" value="Submit" />
        </div>

        @if (Model.FizzBuzzList != null && Model.FizzBuzzList.Any())
        {
            <section id="fizzBuzzList">

                <div class="table-responsive" style="width:600px;margin-left:485px">
                    <table id="fizzbuzzlisttable" class="table table-striped table-bordered table-responsive">
                        <thead class="">
                            <tr>
                                <th class="text-centre datatable-nosort">FizzBuzz List</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.FizzBuzzList)
                            {
                                <tr>
                                    <td class="text-centre">
                                        @if (item.Description.Contains(" "))
                                        {
                                            var values = @item.Description.Split(' ');
                                            var colors = @item.TextColour.Split(' ');
                                            <span class="@colors[0]">@values[0]</span>
                                            <span class="@colors[1]">@values[1]</span>
                                        }
                                        else
                                        {
                                            <span class="@item.TextColour">@item.Description</span>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>   
                    @Html.PagedListPager(Model.FizzBuzzList, page => Url.Action("GetFizzBuzzList", new { Number = Model.Number, page = page, pageSize = Model.FizzBuzzList.PageSize }))

                    Showing @Model.FizzBuzzList.FirstItemOnPage to @Model.FizzBuzzList.LastItemOnPage of @Model.FizzBuzzList.TotalItemCount                
                </div>
            </section>
        }
    }
</div>

<script src="~/Scripts/jquery-1.9.1.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

FizzBuzzSolution/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content")
    @Styles.Render("~/bootstrapbundle")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <header>
        <div class="content-wrapper">

        </div>
    </header>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/fizzBuzzBundle")    

    @RenderSection("scripts", required: false)
</body>
</html>